### ISSUE TITLE
Missing Taxonomy Content

### ISSUE THREAD

**Issue by akornilotrust** [DelaramGlp/airo#3]
Hello,
I believe the taxonomy you have published on main is missing content.
Looking at this example file: https://github.com/DelaramGlp/airo/blob/main/usecase/usecases.owl#L2537 - you have an "inaccurate prediction risk" ... but in the published taxonomy this Risk does not exist. 
It is also not listed under this file - https://github.com/DelaramGlp/airo/blob/main/documentation-v0.1/ontology.ttl

Is there a full list of actual Risks available somewhere?

The actual https://w3id.org/AIRO is missing most of the content right now (eg Risk Sources)

**Comment by akornilotrust** [comment]
Additional context:
Your paper lists that you have identified "47 Risk Sources" but these are not published anywhere - could you share them please?

**Comment by DelaramGlp** [comment]
> Hello, I believe the taxonomy you have published on main is missing content. Looking at this example file: https://github.com/DelaramGlp/airo/blob/main/usecase/usecases.owl#L2537 - you have an "inaccurate prediction risk" ... but in the published taxonomy this Risk does not exist. It is also not listed under this file - https://github.com/DelaramGlp/airo/blob/main/documentation-v0.1/ontology.ttl
> 
> Is there a full list of actual Risks available somewhere?
> 
> The actual https://w3id.org/AIRO is missing most of the content right now (eg Risk Sources)

Hi,

I have moved the instances to `VAIR` (Vocabulary of AI Risks) which is available at https://w3id.org/vair. The main concepts for describing AI use cases and their risks are represented in `AIRO` and instances of these concepts are represented in `VAIR`. 

Thanks for pointing out the issue with the use case. The use cases should be updated to reflect this change. I am going to open an issue in this regard and update the use cases soon.

**Comment by akornilotrust** [comment]
Thank you for the link to the new taxonomy!
